version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: gateway
      POSTGRES_DB: gateway
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  mock:
    build:
      context: ./mock
      dockerfile: Dockerfile
    environment: {}
    ports:
      - "9090:9090"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://gateway:gateway@postgres:5432/gateway?sslmode=disable
      GATEWAY_RESOURCE_AUDIENCE: http://localhost:8080/proxy
      ADMIN_TOKEN: ${ADMIN_TOKEN:-changeme}
      MOCK_BASE_URL: http://mock:9090
      UNPROTECTED: "1"
    depends_on:
      postgres:
        condition: service_healthy
      mock:
        condition: service_started
    ports:
      - "8080:8080"

volumes:
  pgdata: {}
  redisdata: {}


